[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm -r --filter './packages/**' build",
  "pnpm -C apps/web run build"
]

[start]
cmd = "pnpm -C apps/web start"
