# Generated by Django 4.2.29 on 2026-08-19

from django.db import migrations, models


def normalize_internal_roles(apps, schema_editor):
    for model_name in (
        "WorkspaceMember",
        "WorkspaceMemberInvite",
        "ProjectMember",
        "ProjectMemberInvite",
    ):
        model = apps.get_model("db", model_name)
        unknown_roles = list(
            model._base_manager.exclude(role__in=[5, 10, 15, 20])
            .order_by()
            .values_list("role", flat=True)
            .distinct()
        )
        if unknown_roles:
            raise RuntimeError(f"Cannot retire unknown {model_name} roles: {unknown_roles}")
        model._base_manager.filter(role__in=[5, 10]).update(role=15)

    project = apps.get_model("db", "Project")
    project._base_manager.filter(guest_view_all_features=True).update(guest_view_all_features=False)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0127_workspacecalendarevent"),
    ]

    operations = [
        migrations.RunPython(normalize_internal_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="projectmember",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(20, "Admin"), (15, "Member")],
                default=15,
            ),
        ),
        migrations.AlterField(
            model_name="projectmemberinvite",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(20, "Admin"), (15, "Member")],
                default=15,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(20, "Admin"), (15, "Member")],
                default=15,
            ),
        ),
        migrations.AlterField(
            model_name="workspacememberinvite",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(20, "Admin"), (15, "Member")],
                default=15,
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.CheckConstraint(
                check=models.Q(role__in=[15, 20]),
                name="project_member_internal_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmemberinvite",
            constraint=models.CheckConstraint(
                check=models.Q(role__in=[15, 20]),
                name="project_member_invite_internal_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacemember",
            constraint=models.CheckConstraint(
                check=models.Q(role__in=[15, 20]),
                name="workspace_member_internal_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacememberinvite",
            constraint=models.CheckConstraint(
                check=models.Q(role__in=[15, 20]),
                name="workspace_member_invite_internal_role",
            ),
        ),
    ]
