# Generated by Django 5.2 for Hotone credential-log hardening.

from django.db import migrations
from django.db.models import F, Value
from django.db.models.functions import Replace


LOG_TEXT_FIELDS = (
    "path",
    "query_params",
    "headers",
    "body",
    "response_body",
    "user_agent",
)
TOKEN_PATTERN = r"plane_api_[0-9a-fA-F]{32}"


def redact_postgres_api_activity_logs(apps, schema_editor):
    api_token_model = apps.get_model("db", "APIToken")
    activity_model = apps.get_model("db", "APIActivityLog")
    for token_id, raw_token in api_token_model.objects.values_list("id", "token").iterator(chunk_size=500):
        if not raw_token:
            continue
        safe_identifier = f"api-token:{token_id}"
        activity_model.objects.filter(token_identifier=raw_token).update(token_identifier=safe_identifier)
        for field in LOG_TEXT_FIELDS:
            activity_model.objects.filter(**{f"{field}__contains": raw_token}).update(
                **{
                    field: Replace(
                        F(field),
                        Value(raw_token),
                        Value("[REDACTED]"),
                    )
                }
            )
    activity_model.objects.filter(token_identifier__startswith="plane_api_").update(
        token_identifier="api-token:legacy-redacted"
    )
    table = schema_editor.quote_name(activity_model._meta.db_table)
    for field in LOG_TEXT_FIELDS:
        column = schema_editor.quote_name(field)
        schema_editor.execute(
            f"""
            UPDATE {table}
            SET {column} = regexp_replace({column}, %s, '[REDACTED]', 'g')
            WHERE {column} ~ %s
            """,
            [TOKEN_PATTERN, TOKEN_PATTERN],
        )


class Migration(migrations.Migration):
    dependencies = [("db", "0129_hotonetaskstatecommand")]

    operations = [
        migrations.RunPython(
            redact_postgres_api_activity_logs,
            reverse_code=migrations.RunPython.noop,
        )
    ]
